name = "Chilly Peaks Modpack"
author = "oskardotglobal, RealSonarX"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9706fd0cbe33fb747caaed1a21945053d280619b283972db947fb2ac7c21048"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
